FROM nginx:1.30.5-alpine
ARG FVS_NGINX_CONF=python.conf
COPY frontend/ /usr/share/nginx/html/
COPY deploy/nginx/${FVS_NGINX_CONF} /etc/nginx/conf.d/default.conf
COPY deploy/web-entrypoint.sh /fvs-entrypoint.sh
RUN chmod 0555 /fvs-entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/bin/sh","/fvs-entrypoint.sh"]
