typedef unsigned long size_t;
typedef struct fvs_ctx fvs_ctx;
fvs_ctx *fvs_ctx_open(const char*, unsigned int, const char*, const char*, const char*, unsigned int);
void fvs_ctx_close(fvs_ctx*);
const char *fvs_last_error(fvs_ctx*);
const char *fvs_version(void);
const char *fvs_status_name(int);
int fvs_ping(fvs_ctx*);
int fvs_inventory_search_v2(fvs_ctx*,const char*,const char*,const char*,unsigned int,const char*,const char*,const char*,const char*,const char*,const char*,const char*,unsigned int,double,unsigned int,long long,long long,double,double,double,double,int,const char*,unsigned int,unsigned int,char*,size_t);
int fvs_inventory_suggest(fvs_ctx*,const char*,unsigned int,char*,size_t);
int fvs_inventory_discovery_meta_upsert(fvs_ctx*,const char*,int,double,double,const char*,const char*,unsigned int,double,unsigned int);
int fvs_inventory_search(fvs_ctx*,const char*,const char*,unsigned int,char*,size_t);
int fvs_inventory_upsert_v2(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,unsigned int,const char*,const char*,unsigned int,long long,const char*,const char*,const char*,const char*,int,int*);
int fvs_inventory_upsert(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,unsigned int,long long,const char*,const char*,const char*,const char*,int,int*);
int fvs_cart_create(fvs_ctx*,char*,size_t,char*,size_t);
int fvs_cart_get(fvs_ctx*,const char*,const char*,char*,size_t);
int fvs_cart_add(fvs_ctx*,const char*,const char*,const char*,unsigned int,unsigned int,char*,size_t);
int fvs_cart_remove(fvs_ctx*,const char*,const char*,const char*,char*,size_t);
int fvs_checkout_begin(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,unsigned int,char*,size_t);
int fvs_checkout_attach_provider(fvs_ctx*,const char*,const char*,const char*,const char*,const char*);
int fvs_checkout_get(fvs_ctx*,const char*,const char*,char*,size_t);
int fvs_payment_confirm(fvs_ctx*,const char*,const char*,const char*,long long,const char*,unsigned long long,char*,size_t);
int fvs_webhook_claim_v2(fvs_ctx*,const char*,const char*,const char*,unsigned int,char*,size_t,int*);
int fvs_webhook_complete_v2(fvs_ctx*,const char*,const char*,const char*,const char*,int,const char*);
int fvs_outbox_claim(fvs_ctx*,const char*,unsigned int,char*,size_t);
int fvs_outbox_ack(fvs_ctx*,const char*,const char*,const char*);
int fvs_outbox_nack(fvs_ctx*,const char*,const char*,const char*,const char*);
int fvs_order_get(fvs_ctx*,const char*,char*,size_t);
int fvs_maintenance_sweep(fvs_ctx*,unsigned int,unsigned int*,unsigned int*);

int fvs_schema_status(fvs_ctx*,const char*,char*,size_t);
int fvs_ops_snapshot(fvs_ctx*,unsigned int,char*,size_t);
int fvs_worker_heartbeat(fvs_ctx*,const char*,const char*,const char*);
int fvs_worker_goodbye(fvs_ctx*,const char*,const char*);
int fvs_outbox_requeue_dead(fvs_ctx*,const char*,const char*);
int fvs_manual_review_list(fvs_ctx*,unsigned int,char*,size_t);
int fvs_ops_action_record(fvs_ctx*,const char*,const char*,const char*);

int fvs_support_thread_create(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,char*,size_t,char*,size_t);
int fvs_support_thread_get(fvs_ctx*,const char*,const char*,char*,size_t);
int fvs_support_thread_context(fvs_ctx*,const char*,char*,size_t);
int fvs_support_customer_message(fvs_ctx*,const char*,const char*,const char*,char*,size_t);
int fvs_support_ai_message(fvs_ctx*,const char*,const char*,const char*,unsigned int,unsigned int,char*,size_t);
int fvs_support_handoff(fvs_ctx*,const char*,const char*);
int fvs_support_agent_heartbeat(fvs_ctx*,const char*,const char*,const char*,unsigned int);
int fvs_support_queue_list(fvs_ctx*,unsigned int,char*,size_t);
int fvs_support_agent_claim(fvs_ctx*,const char*,const char*);
int fvs_support_agent_message(fvs_ctx*,const char*,const char*,const char*,int,char*,size_t);
int fvs_support_thread_resolve(fvs_ctx*,const char*,const char*);
int fvs_marketing_campaign_create(fvs_ctx*,const char*,const char*,const char*,long long,long long,const char*,const char*,const char*,char*,size_t);
int fvs_marketing_campaign_list(fvs_ctx*,unsigned int,char*,size_t);
int fvs_marketing_campaign_approve(fvs_ctx*,const char*,const char*);
int fvs_marketing_creative_add(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,int,const char*,char*,size_t);
int fvs_marketing_creative_approve(fvs_ctx*,const char*,const char*);
int fvs_marketing_job_schedule(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,char*,size_t);
int fvs_marketing_job_claim(fvs_ctx*,const char*,unsigned int,char*,size_t);
int fvs_marketing_job_ack(fvs_ctx*,const char*,const char*,const char*,const char*);
int fvs_marketing_job_nack(fvs_ctx*,const char*,const char*,const char*,const char*);
int fvs_marketing_metric_upsert(fvs_ctx*,const char*,const char*,const char*,unsigned long long,unsigned long long,long long,unsigned long long,unsigned long long,long long,const char*);
int fvs_marketing_attribution_record(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,long long,const char*,const char*,const char*,const char*,const char*,const char*);
int fvs_marketing_dashboard(fvs_ctx*,unsigned int,char*,size_t);
int fvs_commerce_event_record(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,long long,const char*,const char*,int,const char*);
int fvs_commerce_funnel_dashboard(fvs_ctx*,unsigned int,char*,size_t);
/* Commerce Experience 6.x */
int fvs_commerce_home(fvs_ctx*,char*,size_t);
int fvs_commerce_collection_get(fvs_ctx*,const char*,char*,size_t);
int fvs_commerce_recommendations(fvs_ctx*,const char*,unsigned int,char*,size_t);
int fvs_cart_apply_code(fvs_ctx*,const char*,const char*,const char*,char*,size_t);
int fvs_cart_addon_set(fvs_ctx*,const char*,const char*,const char*,unsigned int,char*,size_t);
int fvs_cart_set_origin(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*);
int fvs_commerce_promotion_upsert(fvs_ctx*,const char*,const char*,const char*,long long,long long,long long,const char*,const char*,const char*,unsigned long long,int,const char*,const char*);
int fvs_commerce_collection_upsert(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,int,int,const char*);
int fvs_social_catalog_feed(fvs_ctx*,const char*,unsigned int,unsigned int,char*,size_t);
int fvs_social_sales_link_create(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,char*,size_t);
int fvs_social_sales_link_resolve(fvs_ctx*,const char*,char*,size_t);
int fvs_social_lead_capture(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,char*,size_t);

int fvs_seo_rebuild_inventory(fvs_ctx*,const char*,unsigned int*);
int fvs_seo_page_upsert(fvs_ctx*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,const char*,int,const char*);
int fvs_seo_page_get(fvs_ctx*,const char*,const char*,char*,size_t);
int fvs_seo_pages_list(fvs_ctx*,unsigned int,char*,size_t);
int fvs_seo_redirect_get(fvs_ctx*,const char*,char*,size_t);
