<?php declare(strict_types=1);
require __DIR__.'/Core.php';require __DIR__.'/Payments.php';require __DIR__.'/InventoryImport.php';require __DIR__.'/Enterprise.php';
const MAX_BODY=8388608;
final class WebhookBusyException extends RuntimeException {}
function adminOk():bool{$sup=$_SERVER['HTTP_X_ADMIN_KEY']??'';$expectedHash=strtolower(trim((string)(getenv('FVS_ADMIN_KEY_SHA256')?:'')));if($expectedHash!=='')return hash_equals($expectedHash,hash('sha256',$sup));if((getenv('FVS_ENV')?:'development')==='production')return false;$expected=getenv('FVS_ADMIN_KEY')?:'';return $expected!==''&&hash_equals($expected,$sup);}
function publicAttempt(array $a):array{$keep=['attempt_id','cart_version','provider','status','requires_confirmation','subtotal_minor','addons_minor','discount_minor','amount_minor','promo_code','source_channel','currency','client_secret','redirect_url','order_id'];$out=[];foreach($keep as $k)if(array_key_exists($k,$a))$out[$k]=$a[$k];return $out;}
function socialFeedOk():bool{$sup=(string)($_SERVER['HTTP_X_SOCIAL_FEED_KEY']??'');$hash=strtolower(trim((string)(getenv('FVS_SOCIAL_FEED_KEY_SHA256')?:'')));if($hash==='')return (getenv('FVS_ENV')?:'development')!=='production';return hash_equals($hash,hash('sha256',$sup));}
function socialInboundOk(string $raw):bool{$secret=(string)(getenv('FVS_SOCIAL_INBOUND_SECRET')?:'');$sup=(string)($_SERVER['HTTP_X_FVS_SIGNATURE']??'');if($secret===''||!str_starts_with($sup,'sha256='))return false;return hash_equals(hash_hmac('sha256',$raw,$secret),strtolower(substr($sup,7)));}
function metricsPayload(array $s):string{$m=[['manual_review_carts','fvs_manual_review_carts','Carts requiring manual payment review'],['manual_review_payments','fvs_manual_review_payments','Payment attempts requiring manual review'],['outbox_dead','fvs_outbox_dead','Dead-letter outbox events'],['outbox_retry_due','fvs_outbox_retry_due','Outbox events currently due for retry'],['outbox_processing_stale','fvs_outbox_processing_stale','Outbox events with expired processing leases'],['webhook_stale','fvs_webhook_stale','Webhook events with expired processing leases'],['holds_expiring_5m','fvs_holds_expiring_5m','Inventory holds expiring within five minutes'],['workers','fvs_workers','Registered worker instances'],['workers_stale','fvs_workers_stale','Worker instances whose heartbeat is stale']];$out=[];foreach($m as [$k,$n,$h]){$out[]="# HELP $n $h";$out[]="# TYPE $n gauge";$out[]=$n.' '.(int)($s[$k]??0);}$out[]='# HELP fvs_ops_degraded Whether the operational snapshot is degraded';$out[]='# TYPE fvs_ops_degraded gauge';$out[]='fvs_ops_degraded '.(($s['status']??'')==='ok'?0:1);return implode("\n",$out)."\n";}
function respondText(int $code,string $body,string $type='text/plain; charset=utf-8',string $cache='no-store'):never{http_response_code($code);header('Content-Type: '.$type);header('Cache-Control: '.$cache);header('X-Content-Type-Options: nosniff');echo $body;exit;}
function envInt(string $k,int $d):int{$v=getenv($k);return $v===false?$d:(int)$v;}
function reqId():string{$v=trim((string)($_SERVER['HTTP_X_REQUEST_ID']??''));return preg_match('/^[A-Za-z0-9._:-]{1,128}$/D',$v)?$v:bin2hex(random_bytes(12));}
function respond(int $code,array $data,?string $cookie=null):never{
    http_response_code($code);header('Content-Type: application/json; charset=utf-8');if(isset($data['request_id']))header('X-Request-ID: '.(string)$data['request_id']);header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: same-origin');header('X-Frame-Options: DENY');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');
    if($cookie!==null)setcookie('fvs_cart_secret',$cookie,['expires'=>time()+86400,'path'=>'/api/v1/cart','secure'=>(getenv('FVS_COOKIE_SECURE')==='1'),'httponly'=>true,'samesite'=>'Lax']);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;
}
function bodyRaw():string{$n=(int)($_SERVER['CONTENT_LENGTH']??0);if($n<0||$n>MAX_BODY)throw new LengthException('too large');$r=file_get_contents('php://input');return is_string($r)?$r:'';}
function bodyJson():array{$r=bodyRaw();if($r==='')return []; $v=json_decode($r,true,512,JSON_THROW_ON_ERROR);return is_array($v)?$v:[];}
function requireOrigin():void{$allowed=array_filter(array_map('trim',explode(',',getenv('FVS_ALLOWED_ORIGINS')?:'http://localhost:8080')));$o=$_SERVER['HTTP_ORIGIN']??'';if($o===''||!in_array($o,$allowed,true))throw new DomainException('origin');}
function providerPrepare(FvsCore $core,array $a,string $secret):array{$pub=rtrim(getenv('FVS_PUBLIC_BASE_URL')?:'http://localhost:8080','/');$api=rtrim(getenv('FVS_API_BASE_URL')?:$pub,'/');$p=$a['provider']==='stripe'?stripePrepare($a):mpPrepare($a,$api.'/api/v1/webhooks/mercadopago',$pub.'/?checkout=return');$core->checkoutAttach($a['attempt_id'],$p['checkout_id'],$p['payment_id'],$p['client_secret'],$p['redirect_url']);return publicAttempt($core->checkoutGet($a['cart_id'],$secret));}
function stripeWebhook(FvsCore $core,string $raw):array{stripeVerify($raw,$_SERVER['HTTP_STRIPE_SIGNATURE']??'',getenv('STRIPE_WEBHOOK_SECRET')?:'');$e=json_decode($raw,true,512,JSON_THROW_ON_ERROR);$eid=(string)($e['id']??'');if($eid==='')throw new InvalidArgumentException('event id');$owner=bin2hex(random_bytes(16));[$claim,$leaseToken]=$core->webhookClaim('stripe',$eid,$owner);if($claim===2)throw new WebhookBusyException('webhook busy');if($claim===3)return ['received'=>true,'duplicate'=>true];try{if(($e['type']??'')!=='payment_intent.succeeded'){$core->webhookComplete('stripe',$eid,$owner,$leaseToken,true);return ['received'=>true,'ignored'=>true];}$pid=(string)($e['data']['object']['id']??'');$pi=stripeFetch($pid);if(($pi['status']??'')!=='succeeded')throw new RuntimeException('not succeeded');$md=$pi['metadata']??[];$aid=(string)($md['attempt_id']??'');$ver=(int)($md['cart_version']??0);if($aid===''||$ver<=0)throw new RuntimeException('metadata');$core->checkoutAttach($aid,null,$pid,null,null);$res=$core->paymentConfirm($aid,'stripe',$pid,(int)($pi['amount_received']??$pi['amount']??0),strtoupper((string)($pi['currency']??'')),$ver);$core->webhookComplete('stripe',$eid,$owner,$leaseToken,true);return ['received'=>true,'result'=>$res['status']??''];}catch(Throwable $x){error_log('FVS stripe webhook '.$eid.' '.get_class($x));try{$core->webhookComplete('stripe',$eid,$owner,$leaseToken,false,get_class($x));}catch(Throwable){}throw $x;}}
function mpWebhook(FvsCore $core,string $raw):array{$p=$raw!==''?json_decode($raw,true,512,JSON_THROW_ON_ERROR):[];$did=(string)($_GET['data.id']??$_GET['data_id']??$p['data']['id']??'');$rid=$_SERVER['HTTP_X_REQUEST_ID']??'';mpVerify($_SERVER['HTTP_X_SIGNATURE']??'',$rid,$did,getenv('MERCADOPAGO_WEBHOOK_SECRET')?:'');$eid=(string)($p['id']??($rid.':'.$did));$owner=bin2hex(random_bytes(16));[$claim,$leaseToken]=$core->webhookClaim('mercadopago',$eid,$owner);if($claim===2)throw new WebhookBusyException('webhook busy');if($claim===3)return ['received'=>true,'duplicate'=>true];try{$pay=mpFetch($did);if(($pay['status']??'')!=='approved'){$core->webhookComplete('mercadopago',$eid,$owner,$leaseToken,true);return ['received'=>true,'ignored'=>true];}$aid=(string)($pay['external_reference']??'');$md=$pay['metadata']??[];$ver=(int)($md['cart_version']??0);if($aid===''||$ver<=0||(string)($md['attempt_id']??'')!==$aid)throw new RuntimeException('metadata');$amount=rawNumberMinor((string)$pay['_raw'],'transaction_amount');$pid=(string)($pay['id']??$did);$core->checkoutAttach($aid,null,$pid,null,null);$res=$core->paymentConfirm($aid,'mercadopago',$pid,$amount,strtoupper((string)($pay['currency_id']??'')),$ver);$core->webhookComplete('mercadopago',$eid,$owner,$leaseToken,true);return ['received'=>true,'result'=>$res['status']??''];}catch(Throwable $x){error_log('FVS mp webhook '.$eid.' '.get_class($x));try{$core->webhookComplete('mercadopago',$eid,$owner,$leaseToken,false,get_class($x));}catch(Throwable){}throw $x;}}

$id=reqId();$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
try{
    if($path==='/api/v1/health/live'&&$method==='GET'){$probe=new FvsCore(false);respond(200,['ok'=>true,'core'=>$probe->version(),'request_id'=>$id]);}
    $core=new FvsCore();
    if($path==='/api/v1/health/ready'&&$method==='GET'){$state=$core->schemaStatus(getenv('FVS_SCHEMA_REQUIRED')?:'001_current.sql');$code=!empty($state['ready'])?200:503;if($code===503)header('Retry-After: 5');respond($code,$state+['request_id'=>$id]);}
    if($path==='/robots.txt'&&$method==='GET'){$base=rtrim(getenv('FVS_PUBLIC_BASE_URL')?:'http://localhost:8080','/');respondText(200,"User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /admin.html\nDisallow: /support-agent.html\nSitemap: {$base}/sitemap.xml\n",'text/plain; charset=utf-8','public,max-age=3600');}
    if($path==='/sitemap.xml'&&$method==='GET'){respondText(200,sitemapXml($core->seoPagesList(50000)['pages']??[]),'application/xml; charset=utf-8','public,max-age=300,stale-while-revalidate=3600');}
    if(preg_match('#^/stay/([a-z0-9-]{1,220})$#',$path,$sm)&&$method==='GET'){try{$page=$core->seoPageGet($sm[1],(string)($_GET['lang']??'es-MX'));respondText(200,seoHtml($page),'text/html; charset=utf-8','public,max-age=300,stale-while-revalidate=86400');}catch(CoreException $x){if($x->coreCode!==3)throw $x;try{$r=$core->seoRedirectGet($path);http_response_code((int)($r['status_code']??301));header('Location: '.(string)$r['target_path']);header('Cache-Control: public,max-age=3600');exit;}catch(CoreException $rx){if($rx->coreCode!==3)throw $rx;respondText(404,'Not found','text/plain; charset=utf-8','public,max-age=60');}}}
    if($path==='/api/v1/commerce/home'&&$method==='GET')respond(200,$core->commerceHome()+['request_id'=>$id]);
    if(preg_match('#^/api/v1/commerce/collections/([A-Za-z0-9_-]{1,120})$#',$path,$cc)&&$method==='GET')respond(200,$core->commerceCollectionGet($cc[1])+['request_id'=>$id]);
    if($path==='/api/v1/commerce/recommendations'&&$method==='GET')respond(200,$core->commerceRecommendations((string)($_GET['slot_id']??''),max(1,min(30,(int)($_GET['limit']??8))))+['request_id'=>$id]);
    if(preg_match('#^/s/([0-9a-fA-F]{32})$#',$path,$sl)&&$method==='GET'){$r=$core->socialSalesLinkResolve($sl[1]);http_response_code(302);header('Location: '.(string)($r['path']??'/'));header('Cache-Control: no-store');header('Referrer-Policy: same-origin');exit;}
    if(preg_match('#^/api/v1/social/catalog/([A-Za-z0-9_-]{1,32})$#',$path,$sf)&&$method==='GET'){if(!socialFeedOk())respond(401,['error'=>'social_feed_auth','request_id'=>$id]);respond(200,$core->socialCatalogFeed($sf[1],max(1,min(1000,(int)($_GET['limit']??500))),max(0,(int)($_GET['offset']??0)))+['request_id'=>$id]);}
    if($path==='/api/v1/social/inbound'&&$method==='POST'){$raw=bodyRaw();if(!socialInboundOk($raw))respond(401,['error'=>'social_signature','request_id'=>$id]);$b=json_decode($raw,true,512,JSON_THROW_ON_ERROR);respond(202,$core->socialLeadCapture(is_array($b)?$b:[])+['request_id'=>$id]);}
    if($path==='/api/v1/support'&&$method==='POST'){requireOrigin();$b=bodyJson();[$tid,$sec]=$core->supportThreadCreate((string)($b['email']??''),(string)($b['subject']??'Ayuda con mi reserva'),(string)($b['cart_id']??''),(string)($b['order_id']??''),(string)($b['priority']??'normal'));if((getenv('FVS_SUPPORT_AI_ENABLED')?:'1')!=='1')$core->supportHandoff($tid,'AI support disabled; human handoff');supportRespond(201,['thread_id'=>$tid,'status'=>'open','request_id'=>$id],$sec);}
    if(preg_match('#^/api/v1/support/([0-9a-fA-F-]{36})(?:/(messages))?$#',$path,$sm)){if($method==='POST')requireOrigin();$sec=$_COOKIE['fvs_support_secret']??'';if($sec==='')respond(401,['error'=>'support_session_missing','request_id'=>$id]);if(($sm[2]??'')===''&&$method==='GET')respond(200,$core->supportThreadGet($sm[1],$sec)+['request_id'=>$id]);if(($sm[2]??'')==='messages'&&$method==='POST'){$b=bodyJson();respond(202,$core->supportCustomerMessage($sm[1],$sec,(string)($b['body']??''))+['request_id'=>$id]);}}
    if($path==='/api/v1/marketing/event'&&$method==='POST'){requireOrigin();$b=bodyJson();$core->marketingAttributionRecord($b);respond(202,['accepted'=>true,'request_id'=>$id]);}
    if(str_starts_with($path,'/api/v1/webhooks/')&&$method==='POST'){$raw=bodyRaw();$r=str_ends_with($path,'/stripe')?stripeWebhook($core,$raw):(str_ends_with($path,'/mercadopago')?mpWebhook($core,$raw):null);if($r===null)respond(404,['error'=>'not_found','request_id'=>$id]);respond(200,$r+['request_id'=>$id]);}
    if(in_array($method,['POST','PUT','PATCH','DELETE'],true))requireOrigin();
    if(str_starts_with($path,'/api/v1/agent/')){if(!agentOk())respond(401,['error'=>'agent_auth','request_id'=>$id]);$aid=agentId();if($aid==='')respond(400,['error'=>'agent_id_required','request_id'=>$id]);if($path==='/api/v1/agent/heartbeat'&&$method==='POST'){$b=bodyJson();$core->supportAgentHeartbeat($aid,(string)($b['display_name']??$aid),(string)($b['status']??'available'),(int)($b['max_active']??5));respond(204,[]);}if($path==='/api/v1/agent/queue'&&$method==='GET')respond(200,$core->supportQueueList(200)+['request_id'=>$id]);if(preg_match('#^/api/v1/agent/threads/([0-9a-fA-F-]{36})(?:/(claim|messages|resolve))?$#',$path,$am)){if(($am[2]??'')===''&&$method==='GET')respond(200,$core->supportThreadContext($am[1])+['request_id'=>$id]);if(($am[2]??'')==='claim'&&$method==='POST'){$core->supportAgentClaim($am[1],$aid);respond(200,$core->supportThreadContext($am[1])+['request_id'=>$id]);}if(($am[2]??'')==='messages'&&$method==='POST'){$b=bodyJson();respond(200,$core->supportAgentMessage($am[1],$aid,(string)($b['body']??''),!empty($b['internal']))+['request_id'=>$id]);}if(($am[2]??'')==='resolve'&&$method==='POST'){$core->supportThreadResolve($am[1],$aid);respond(200,$core->supportThreadContext($am[1])+['request_id'=>$id]);}}}
    if($path==='/api/v1/admin/marketing/campaigns'&&$method==='GET'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);respond(200,$core->marketingCampaignList(200)+['request_id'=>$id]);}
    if($path==='/api/v1/admin/marketing/campaigns'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$b=bodyJson();$actor=substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128);respond(201,$core->marketingCampaignCreate((string)($b['name']??''),(string)($b['objective']??'bookings'),(string)($b['automation_mode']??'guarded'),(int)($b['budget_minor']??0),(int)($b['daily_budget_minor']??0),(string)($b['currency']??'MXN'),(string)($b['utm_campaign']??''),$actor)+['request_id'=>$id]);}
    if(preg_match('#^/api/v1/admin/marketing/campaigns/([0-9a-fA-F-]{36})/approve$#',$path,$cm)&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$core->marketingCampaignApprove($cm[1],substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128));respond(200,['status'=>'approved','request_id'=>$id]);}
    if(preg_match('#^/api/v1/admin/marketing/campaigns/([0-9a-fA-F-]{36})/(configure|pause)$#',$path,$cg)&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$actor=substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128);if($cg[2]==='configure'){$core->marketingCampaignConfigure($cg[1],bodyJson(),$actor);respond(200,['status'=>'configured','request_id'=>$id]);}$core->marketingCampaignPause($cg[1],$actor);respond(200,['status'=>'paused','request_id'=>$id]);}
    if($path==='/api/v1/admin/marketing/creatives'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$b=bodyJson();$actor=substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128);respond(201,$core->marketingCreativeAdd((string)($b['campaign_id']??''),(string)($b['channel']??''),(string)($b['variant_key']??'A'),(string)($b['headline']??''),(string)($b['body']??''),(string)($b['cta']??''),(string)($b['landing_url']??''),(string)($b['image_url']??''),!empty($b['ai_generated']),$actor)+['request_id'=>$id]);}
    if(preg_match('#^/api/v1/admin/marketing/creatives/([0-9a-fA-F-]{36})/approve$#',$path,$cr)&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$core->marketingCreativeApprove($cr[1],substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128));respond(200,['status'=>'approved','request_id'=>$id]);}
    if($path==='/api/v1/admin/marketing/jobs'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$b=bodyJson();$actor=substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'marketing-admin'),0,128);respond(201,$core->marketingJobSchedule((string)($b['campaign_id']??''),(string)($b['creative_id']??''),(string)($b['channel']??''),(string)($b['action']??'publish'),(string)($b['scheduled_at']??''),(array)($b['payload']??[]),$actor)+['request_id'=>$id]);}
    if($path==='/api/v1/admin/marketing/dashboard'&&$method==='GET'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);respond(200,$core->marketingDashboard(max(1,min(730,(int)($_GET['days']??30))))+['request_id'=>$id]);}
    if($path==='/api/v1/admin/commerce/promotions'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$core->commercePromotionUpsert(bodyJson(),substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'commerce-admin'),0,128));respond(200,['status'=>'upserted','request_id'=>$id]);}
    if($path==='/api/v1/admin/commerce/collections'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$core->commerceCollectionUpsert(bodyJson(),substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'commerce-admin'),0,128));respond(200,['status'=>'upserted','request_id'=>$id]);}
    if($path==='/api/v1/admin/social/links'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);respond(201,$core->socialSalesLinkCreate(bodyJson(),substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'social-admin'),0,128))+['request_id'=>$id]);}
    if($path==='/api/v1/admin/seo/rebuild'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$n=$core->seoRebuildInventory(substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'seo-admin'),0,128));respond(200,['upserted'=>$n,'request_id'=>$id]);}
    if($path==='/api/v1/admin/seo/pages'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$core->seoPageUpsert(bodyJson(),substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'seo-admin'),0,128));respond(200,['status'=>'upserted','request_id'=>$id]);}
    if($path==='/api/v1/admin/ops'&&$method==='GET'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$r=$core->opsSnapshot((int)(getenv('FVS_WORKER_STALE_SECONDS')?:90));respond(200,$r+['request_id'=>$id]);}
    if($path==='/api/v1/admin/metrics'&&$method==='GET'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$r=$core->opsSnapshot((int)(getenv('FVS_WORKER_STALE_SECONDS')?:90));respondText(200,metricsPayload($r),'text/plain; version=0.0.4; charset=utf-8');}
    if($path==='/api/v1/admin/manual-review'&&$method==='GET'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$limit=max(1,min(200,(int)($_GET['limit']??100)));$r=$core->manualReviewList($limit);respond(200,$r+['request_id'=>$id]);}
    if(preg_match('#^/api/v1/admin/outbox/([0-9a-fA-F-]{36})/requeue$#',$path,$om)&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$actor=substr((string)($_SERVER['HTTP_X_ADMIN_ACTOR']??'api-admin'),0,128);$core->outboxRequeueDead($om[1],$actor);respond(202,['status'=>'requeued','event_id'=>$om[1],'request_id'=>$id]);}
    if($path==='/api/v1/admin/import'&&$method==='POST'){if(!adminOk())respond(401,['error'=>'admin_auth','request_id'=>$id]);$r=importInventoryBytes($core,bodyRaw(),$_SERVER['HTTP_X_FILENAME']??'inventory.csv');respond(200,$r+['request_id'=>$id]);}
    if($path==='/api/v1/search/suggest'&&$method==='GET'){$q=trim((string)($_GET['q']??''));$lim=max(1,min(30,(int)($_GET['limit']??10)));respond(200,($q===''?['suggestions'=>[]]:$core->inventorySuggest($q,$lim))+['request_id'=>$id]);}
    if($path==='/api/v1/inventory'&&$method==='GET'){$bbox=null;if(!empty($_GET['bbox'])){$v=array_map('floatval',explode(',',(string)$_GET['bbox']));if(count($v)===4)$bbox=$v;}$f=['q'=>(string)($_GET['q']??''),'check_in'=>(string)($_GET['check_in']??''),'check_out'=>(string)($_GET['check_out']??''),'guests'=>max(1,min(64,(int)($_GET['guests']??2))),'country'=>(string)($_GET['country']??''),'city'=>(string)($_GET['city']??''),'resort'=>(string)($_GET['resort']??''),'property_type'=>(string)($_GET['property_type']??''),'season'=>(string)($_GET['season']??''),'booking_mode'=>(string)($_GET['booking_mode']??''),'amenities'=>(string)($_GET['amenities']??''),'min_bedrooms'=>max(0,min(40,(int)($_GET['min_bedrooms']??0))),'min_bathrooms'=>max(0.0,min(40.0,(float)($_GET['min_bathrooms']??0))),'min_rating_x100'=>max(0,min(500,(int)($_GET['min_rating_x100']??0))),'min_price_minor'=>max(0,(int)($_GET['min_price_minor']??0)),'max_price_minor'=>max(0,(int)($_GET['max_price_minor']??0)),'bbox'=>$bbox,'sort'=>(string)($_GET['sort']??'relevance'),'limit'=>max(1,min(240,(int)($_GET['limit']??60))),'offset'=>max(0,min(10000,(int)($_GET['offset']??0)))];respond(200,$core->inventorySearch($f)+['request_id'=>$id]);}
    if($path==='/api/v1/cart'&&$method==='POST'){[$cid,$sec]=$core->cartCreate();respond(201,['cart_id'=>$cid,'status'=>'open','request_id'=>$id],$sec);}
    if(preg_match('#^/api/v1/cart/([0-9a-fA-F-]{36})(?:/(.*))?$#',$path,$m)){$cid=$m[1];$tail=$m[2]??'';$sec=$_COOKIE['fvs_cart_secret']??'';if($sec==='')respond(401,['error'=>'cart_session_missing','request_id'=>$id]);
        if($tail===''&&$method==='GET')respond(200,$core->cartGet($cid,$sec)+['request_id'=>$id]);
        if($tail==='items'&&$method==='POST'){$b=bodyJson();respond(200,$core->cartAdd($cid,$sec,(string)($b['slot_id']??''),(int)($b['guests']??1),envInt('FVS_HOLD_SECONDS',900))+['request_id'=>$id]);}
        if(preg_match('#^items/([0-9a-fA-F-]{36})$#',$tail,$im)&&$method==='DELETE')respond(200,$core->cartRemove($cid,$sec,$im[1])+['request_id'=>$id]);
        if($tail==='code'&&$method==='POST'){$b=bodyJson();respond(200,$core->cartApplyCode($cid,$sec,(string)($b['code']??''))+['request_id'=>$id]);}
        if(preg_match('#^addons/([A-Za-z0-9_-]{1,64})$#',$tail,$ad)&&in_array($method,['PUT','POST'],true)){$b=bodyJson();respond(200,$core->cartAddonSet($cid,$sec,$ad[1],(int)($b['quantity']??0))+['request_id'=>$id]);}
        if($tail==='origin'&&$method==='POST'){$b=bodyJson();$core->cartSetOrigin($cid,$sec,(string)($b['channel']??''),(string)($b['campaign_id']??''),(string)($b['creative_id']??''),(string)($b['social_token']??''));respond(200,$core->cartGet($cid,$sec)+['request_id'=>$id]);}
        if($tail==='checkout'&&$method==='POST'){$b=bodyJson();if(($b['terms_accepted']??false)!==true)respond(422,['error'=>'terms_required','request_id'=>$id]);$a=$core->checkoutBegin($cid,$sec,(string)($b['provider']??''),(string)($b['email']??''),getenv('FVS_TERMS_VERSION')?:'2026-09-16',envInt('FVS_CHECKOUT_HOLD_SECONDS',1200));if(($a['status']??'')==='quote_refreshed')respond(200,publicAttempt($a)+['request_id'=>$id]);try{$r=providerPrepare($core,$a,$sec);respond(200,$r+['request_id'=>$id]);}catch(ProviderException $x){error_log('FVS provider prepare '.$a['attempt_id'].' '.get_class($x));respond(202,['status'=>'provider_reconciliation_pending','attempt_id'=>$a['attempt_id'],'request_id'=>$id]);}}
        if($tail==='checkout/status'&&$method==='GET'){$a=$core->checkoutGet($cid,$sec);if(in_array($a['status']??'',['creating','pending'],true)){try{$a=providerPrepare($core,$a,$sec);}catch(ProviderException $x){error_log('FVS provider resume '.$a['attempt_id'].' '.get_class($x));}}respond(200,publicAttempt($a)+['request_id'=>$id]);}
    }
    respond(404,['error'=>'not_found','request_id'=>$id]);
}catch(WebhookBusyException){header('Retry-After: 2');respond(503,['error'=>'webhook_busy','request_id'=>$id]);}
catch(DomainException){respond(403,['error'=>'forbidden_origin','request_id'=>$id]);}
catch(UnsupportedMediaTypeException){respond(415,['error'=>'unsupported_file','request_id'=>$id]);}
catch(LengthException){respond(413,['error'=>'payload_too_large','request_id'=>$id]);}
catch(JsonException|InvalidArgumentException|ValueError){respond(400,['error'=>'bad_request','request_id'=>$id]);}
catch(CoreException $x){error_log('FVS core '.$x->coreCode.' '.$x->getMessage());$map=[1=>400,2=>503,3=>404,4=>409,5=>401,6=>409,7=>409,8=>422,9=>500,10=>500,11=>503];if($x->coreCode===11)header('Retry-After: 1');respond($map[$x->coreCode]??500,['error'=>$x->coreCode===11?'retry':'core_error','request_id'=>$id]);}
catch(ProviderException $x){error_log('FVS provider '.get_class($x));respond(502,['error'=>'payment_provider_error','request_id'=>$id]);}
catch(Throwable $x){error_log('FVS unhandled '.get_class($x).' '.$x->getMessage());respond(500,['error'=>'internal_error','request_id'=>$id]);}
