<?php declare(strict_types=1);
require_once dirname(__DIR__).'/shim-php/Core.php';
$stop=false;if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,function()use(&$stop){$stop=true;});pcntl_signal(SIGINT,function()use(&$stop){$stop=true;});}
function envInt(string $k,int $d):int{$v=getenv($k);return $v===false?$d:(int)$v;}
$instance='marketing:'.gethostname().':'.getmypid();
function envChannel(string $channel):array{$p='FVS_MARKETING_'.strtoupper(str_replace('-','_',$channel));$url=trim((string)(getenv($p.'_URL')?:''));if($url==='')throw new RuntimeException($p.'_URL missing');$headers=['Content-Type: application/json','User-Agent: FVS-marketing/6.0'];$tok=trim((string)(getenv($p.'_TOKEN')?:''));if($tok!=='')$headers[]='Authorization: Bearer '.$tok;$ver=trim((string)(getenv($p.'_VERSION')?:''));if($ver!=='')$headers[]='X-API-Version: '.$ver;return [$url,$headers];}
function postJson(string $url,array $payload,array $headers):array{$raw=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$secret=getenv('FVS_MARKETING_SIGNING_SECRET')?:'';if($secret!=='')$headers[]='X-FVS-Signature: sha256='.hash_hmac('sha256',$raw,$secret);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$raw,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>envInt('FVS_MARKETING_HTTP_TIMEOUT',20),CURLOPT_FAILONERROR=>false]);$body=curl_exec($ch);if($body===false){$e=curl_error($ch);curl_close($ch);throw new RuntimeException('provider transport: '.$e);}$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($code<200||$code>=300)throw new RuntimeException('provider_http_'.$code);if($body==='')return ['ok'=>true];$j=json_decode($body,true,512,JSON_THROW_ON_ERROR);return is_array($j)?$j:[];}
function dispatchMarketing(FvsCore $core,array $j):string{[$url,$headers]=envChannel((string)$j['channel']);$provider=$j['payload']??[];if(($j['action']??'')==='sync_catalog'){$provider=array_merge($provider,['catalog'=>$core->socialCatalogFeed((string)$j['channel'],500,0)]);}elseif(($j['action']??'')==='publish_collection'&&!empty($provider['collection_slug'])){$provider=array_merge($provider,['collection'=>$core->commerceCollectionGet((string)$provider['collection_slug'])]);}$payload=['schema'=>'fvs.marketing.job.v2','job_id'=>$j['job_id'],'campaign_id'=>$j['campaign_id'],'creative_id'=>$j['creative_id']??null,'channel'=>$j['channel'],'action'=>$j['action'],'campaign_name'=>$j['campaign_name']??'','creative'=>['headline'=>$j['headline']??'','body'=>$j['body']??'','cta'=>$j['cta']??'','landing_url'=>$j['landing_url']??'','image_url'=>$j['image_url']??''],'provider_payload'=>$provider,'guardrails'=>$j['guardrails']??[]];$r=postJson($url,$payload,$headers);if(($j['action']??'')==='sync_metrics'&&is_array($r['metrics']??null)){$m=$r['metrics'];$core->marketingMetricUpsert((string)$j['campaign_id'],(string)$j['channel'],(string)($m['metric_date']??gmdate('Y-m-d')),(int)($m['impressions']??0),(int)($m['clicks']??0),(int)($m['spend_minor']??0),(int)($m['leads']??0),(int)($m['bookings']??0),(int)($m['revenue_minor']??0),(string)($m['currency']??'MXN'));$core->experimentSnapshot((string)$j['campaign_id'],30);}return substr((string)($r['id']??$r['provider_ref']??$r['campaign_id']??''),0,191);}
$core=new FvsCore();$idle=max(.2,(float)(getenv('FVS_MARKETING_IDLE_SECONDS')?:2));$hb=max(5,(float)(getenv('FVS_WORKER_HEARTBEAT_SECONDS')?:15));$next=0.0;$growthEvery=max(60,envInt('FVS_GROWTH_LOOP_SECONDS',300));$nextGrowth=0.0;while(!$stop){$now=microtime(true);if($now>=$next){try{$core->workerHeartbeat('marketing',$instance);$core->abandonmentScan(envInt('FVS_ABANDONMENT_IDLE_SECONDS',1800),envInt('FVS_ABANDONMENT_SCAN_LIMIT',50));}catch(Throwable $e){error_log('marketing heartbeat/scanner '.get_class($e));}$next=$now+$hb;}if($now>=$nextGrowth){try{$core->growthLoopRun(envInt('FVS_GROWTH_LOOP_DAYS',7),envInt('FVS_GROWTH_LOOP_LIMIT',50));}catch(Throwable $e){error_log('marketing growth-loop '.get_class($e));}$nextGrowth=$now+$growthEvery;}$owner=$instance.':'.bin2hex(random_bytes(8));$job=$core->marketingJobClaim($owner,envInt('FVS_MARKETING_LEASE_SECONDS',180));if(!$job){usleep((int)($idle*1000000));continue;}try{$ref=dispatchMarketing($core,$job);if(in_array((string)($job['action']??''),['pause','update_budget'],true))$core->growthDecisionApply((string)$job['job_id']);$core->marketingJobAck($job['job_id'],$owner,$job['lease_token'],$ref);}catch(Throwable $e){error_log('marketing job '.($job['job_id']??'').' '.get_class($e));try{$core->marketingJobNack($job['job_id'],$owner,$job['lease_token'],get_class($e));}catch(Throwable){}}}try{$core->workerGoodbye('marketing',$instance);}catch(Throwable){}
